name: MapManager
main: org.inventivetalent.mapmanager.MapManagerPlugin
author: inventivetalent
version: ${project.version}

softdepend: [PacketListenerApi]

commands:
  mapmanager:
    aliases: [mm, mmanager, mapman, mapm]